# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa40ce60331f62f3f81b1d81e65a376adecdbb44135a809598da30de2bad7907fecce406f9b200602227af558bc3afc2f42573149d55c75ebda858fc3c51f9fa

test:
  secret_key_base: 30a906bfba78734725699bc861bd1574b224b6e96c023f23cb7110f2e28a841e45d319d4c7dd915b6ee3d79147093341fb73f4a27383eaffca4d70ee43ac16f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
